In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# 학습 데이터셋을 생성한다.
x_train = torch.FloatTensor([[1], [2], [3], [4]])
y_train = torch.FloatTensor([[50], [70], [90], [85]])

In [3]:
# 단순 선형 회귀는 input=1, output=1
model = nn.Linear(1, 1) # 선형회귀 모델을 생성하는 클래스

In [4]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.8905]], requires_grad=True), Parameter containing:
 tensor([-0.7050], requires_grad=True)]

In [5]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [6]:
epoch_count = 3000
for epoch in range(epoch_count + 1) : 
  H = model(x_train)

  cost = F.mse_loss(H, y_train) # 함수를 통해 평균 제곱 오차를 구한다.

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0 : 
    print(f'Epoch {epoch:4d}/{epoch_count}, Cost:{cost:.6f}')

Epoch    0/3000, Cost:6151.033691
Epoch  100/3000, Cost:156.912842
Epoch  200/3000, Cost:107.284416
Epoch  300/3000, Cost:80.039055
Epoch  400/3000, Cost:65.081703
Epoch  500/3000, Cost:56.870281
Epoch  600/3000, Cost:52.362320
Epoch  700/3000, Cost:49.887455
Epoch  800/3000, Cost:48.528831
Epoch  900/3000, Cost:47.782921
Epoch 1000/3000, Cost:47.373398
Epoch 1100/3000, Cost:47.148624
Epoch 1200/3000, Cost:47.025227
Epoch 1300/3000, Cost:46.957439
Epoch 1400/3000, Cost:46.920265
Epoch 1500/3000, Cost:46.899864
Epoch 1600/3000, Cost:46.888676
Epoch 1700/3000, Cost:46.882481
Epoch 1800/3000, Cost:46.879112
Epoch 1900/3000, Cost:46.877277
Epoch 2000/3000, Cost:46.876251
Epoch 2100/3000, Cost:46.875690
Epoch 2200/3000, Cost:46.875374
Epoch 2300/3000, Cost:46.875175
Epoch 2400/3000, Cost:46.875095
Epoch 2500/3000, Cost:46.875072
Epoch 2600/3000, Cost:46.875034
Epoch 2700/3000, Cost:46.875000
Epoch 2800/3000, Cost:46.874992
Epoch 2900/3000, Cost:46.875015
Epoch 3000/3000, Cost:46.874985


In [7]:
var = torch.FloatTensor([[5.0]])
pred = model(var)
print(f'입력이 5 일때의 예측값 : {pred.item()}')

입력이 5 일때의 예측값 : 105.0030288696289


In [8]:
print(list(model.parameters()))

[Parameter containing:
tensor([[12.5015]], requires_grad=True), Parameter containing:
tensor([42.4957], requires_grad=True)]


In [9]:
x_train = torch.FloatTensor([[2, 0, 0], 
                             [2, 1, 0], 
                             [2, 2, 1], 
                             [3, 1, 1], 
                             [4, 1, 2], 
                             [4, 2, 2]])
y_train = torch.FloatTensor([[50], [60], [65], [70], [75], [85]]) 

In [10]:
model = nn.Linear(3, 1) # 선형회귀 모델을 생성하는 클래스

In [11]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3102,  0.4871, -0.3596]], requires_grad=True),
 Parameter containing:
 tensor([0.0106], requires_grad=True)]

In [12]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)

In [13]:
epoch_count = 1000
for epoch in range(epoch_count + 1) : 

  H = model(x_train)
  cost = F.mse_loss(H, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0 : 
    print(f'Epoch {epoch:4d}/{epoch_count}, Cost:{cost:.6f}')

Epoch    0/1000, Cost:4775.062012
Epoch  100/1000, Cost:38.790882
Epoch  200/1000, Cost:12.672505
Epoch  300/1000, Cost:5.017679
Epoch  400/1000, Cost:2.737749
Epoch  500/1000, Cost:2.037112
Epoch  600/1000, Cost:1.804007
Epoch  700/1000, Cost:1.710575
Epoch  800/1000, Cost:1.659602
Epoch  900/1000, Cost:1.622186
Epoch 1000/1000, Cost:1.589714


In [14]:
var = torch.FloatTensor([[5, 2, 3]])
pred = model(var)
print(f'예측값 : {pred}')

예측값 : tensor([[93.3076]], grad_fn=<AddmmBackward0>)


In [15]:
print(list(model.parameters()))

[Parameter containing:
tensor([[16.0996, 11.6578, -9.3567]], requires_grad=True), Parameter containing:
tensor([17.5639], requires_grad=True)]
