# **1. 텐서플로우(TensorFlow) 와 케라스(Keras)**

* 텐서플로우와 케라스는 ML 모델을 개발하고 학습하는데 도움이 되는 핵심 오픈소스 라이브러리이다.
* 케라스는 사용자가 텐서플로우를 조금 더 쉽고 편하게 사용할 수 있게 해주는 high level API 를 제공한다.
* 텐서플로우 2.x 에서는 케라스를 딥러닝의 공식 API 로 채택하였고, 텐서플로우 내의 하나의 프레임워크로 개발되고 있다.
* 현재는 텐서플로우 2.x 버전을 사용하여 모델을 만든다.

In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
print(tf.__version__)
print(keras.__version__)

2.8.0
2.8.0


### **1-1. Tensor**

* Tensor : 여러 차원의 행렬(multi-dimensional array) 를 나타내는 말이다.
* Tensor 는 Tensorflow 의 기본 데이터타입이다. (dtype=Tensor)

In [5]:
hellotf = tf.constant([3, 3], dtype=tf.float32)
print(hellotf)

hellotf = tf.constant('Hello Tensor!!')
print(hellotf)

tf.Tensor([3. 3.], shape=(2,), dtype=float32)
tf.Tensor(b'Hello Tensor!!', shape=(), dtype=string)


In [6]:
x = tf.constant([[1.0, 2.0],
                 [3.0, 4.0], ])
print(x)
print(type(x))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
import numpy as np

In [9]:
x_np = np.array([[1.0, 2.0], 
                 [3.0, 4.0]])
x_list = [[1.0, 2.0], 
          [3.0, 4.0]]

print(type(x_np), type(x_list))

<class 'numpy.ndarray'> <class 'list'>


In [11]:
x_np = tf.convert_to_tensor(x_np)
x_list = tf.convert_to_tensor(x_list)

print(type(x_np), type(x_list))

<class 'tensorflow.python.framework.ops.EagerTensor'> <class 'tensorflow.python.framework.ops.EagerTensor'>


In [14]:
# tensor 를 np 의 ndarray 로 변환하는 방법
x.numpy()
print(type(x.numpy()))

<class 'numpy.ndarray'>


### **1-2. 텐서플로우 함수**

* 넘파이와 유사한 함수를 가지고 있다.

In [18]:
a = tf.ones((2, 3))
print(a)

b = tf.zeros((2, 3))
print(b)

c = tf.fill((2, 3), 2)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2 2 2]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [22]:
d = tf.zeros_like(c) # shape 와 dtype 이 복사된다.
print(d)

e = tf.ones_like(b)
print(e)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [43]:
g = tf.range(10)
print(f)

h = tf.random.uniform((2, 2)) # 0 ~ 1 사이의 랜덤값
print(h)

i = tf.random.normal((2, 2)) # 3 ~ -3 사이의 랜덤값
print(i)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0.09243691 0.42977118]
 [0.12751567 0.4617387 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-2.951743   -0.02293143]
 [-1.0329878   0.5452521 ]], shape=(2, 2), dtype=float32)


### **1-3. Tensor 의 속성**

In [48]:
tensor = tf.random.normal((3, 4))

print(f'Shape : {tensor.shape}')
print(f'DataType : {tensor.dtype}')

Shape : (3, 4)
DataType : <dtype: 'float32'>


In [49]:
tensor = tf.reshape(tensor, (4, 3))
# tensor = tf.cast(tensor, tf.int32)

print(f'Shape : {tensor.shape}') # 중요하다
print(f'DataType : {tensor.dtype}')
print(tensor) # 빈자리에 0 이 들어가는 것이 아니라 shape 자체를 바꾼다.

Shape : (4, 3)
DataType : <dtype: 'float32'>
tf.Tensor(
[[-0.93266815  0.18797784  1.1654942 ]
 [ 0.5967486   0.03857164 -0.7622829 ]
 [-0.7746055  -0.75063324 -0.9847051 ]
 [-0.40449822  0.95087224  1.6741793 ]], shape=(4, 3), dtype=float32)


### **1-4. Variable**

* 텐서는 기본적으로 상수의 형태로 저장되어 값을 변경할 수 없다.
* Variable 은 변할 수 있는 상태를 저장하는 데에 사용되는 특별한 텐서이다.
* 딥러닝에서는 학습해야 하는 가중치(weight, bias) 등을 variable 로 생성한다.

In [52]:
tensor = tf.ones((3, 4))
print(tensor)

# tensor[0, 0] = 2  # 텐서의 자료형은 '상수' 로, 값을 변경할 수 없다.

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [56]:
variable = tf.Variable(tensor)
print(variable)

variable[2, 2].assign(2)
print(variable)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 2., 1.]], dtype=float32)>


In [58]:
initial_value = tf.random.normal(shape=(2, 2))
weight = tf.Variable(initial_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.24503136, -0.23237978],
       [-0.7059126 ,  0.57637113]], dtype=float32)>


In [61]:
# asssign(value) : 값을 설정
# asssign_add(increment) : 더하기
# asssign_sub(decrement) : 빼기

new_value = tf.random.normal(shape=(2, 2))
print(new_value)

weight.assign(new_value)
print(weight)

added_value = tf.ones(shape=(2, 2))
weight.assign_sub(added_value)
print(weight)

weight.assign_add(added_value)
print(weight)

tf.Tensor(
[[ 1.4153081   0.42933944]
 [-0.2919889  -0.03585619]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.4153081 ,  0.42933944],
       [-0.2919889 , -0.03585619]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.41530812, -0.5706606 ],
       [-1.2919888 , -1.0358562 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.4153081 ,  0.4293394 ],
       [-0.29198885, -0.03585625]], dtype=float32)>


### **1-5. Tensor 의 인덱싱과 슬라이싱**

In [62]:
a = tf.range(1, 13)
print(a)
a = tf.reshape(a, (3, 4))
print(a)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [63]:
# 인덱싱을 하게 되면 차원이 감소하게 된다.
print(a[1])
print(a[0, -1])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [64]:
# 슬라이싱은 차원이 유지된다.
print(a[1:-1])
print(a[:2, 2:])

tf.Tensor([[5 6 7 8]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


### **1-6. transpose(차원 바꾸기) *복습 예정**

In [65]:
a = tf.range(16)
print(a)
a = tf.reshape(a, (2, 2, -1)) # -1 은 자동으로 만들라는 뜻이다.
print(a)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


In [66]:
print(a)
# transpose(전치할 행렬, 차원의 순서, [오퍼레이션 명칭])
b = tf.transpose(a, (2, 0, 1))
print(b)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]], shape=(4, 2, 2), dtype=int32)


### **1-7. Tensor 연산**

In [67]:
x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
y = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
print(x)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [69]:
print(tf.add(x, y))
print(tf.subtract(x, y))
print(tf.multiply(x, y))
print(tf.divide(x, y))
print(tf.matmul(x, y))
print('*' * 50)
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
**************************************************
tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [70]:
z = tf.range(1, 11)
print(z)
z = tf.reshape(z, (2, 5))
print(z)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [72]:
print(tf.reduce_sum(z)) # 요소의 합계

tf.Tensor(55, shape=(), dtype=int32)


In [74]:
sum1 = tf.reduce_sum(z, axis=0)
print(sum1)
sum2 = tf.reduce_sum(z, axis=1)
print(sum2)
sum3 = tf.reduce_sum(z, axis=-1)
print(sum3)

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)


In [78]:
concat = tf.concat([z, z], axis=0)
print(concat)
concat = tf.concat([z, z], axis=1)
print(concat)
concat = tf.concat([z, z], axis=-1)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
