# **1. 파이토치(Pytorch)**

* Pytorch 는 tensorflow 와 함께 딥 러닝에서 가장 널리 사용되는 framework 이다.
* 초기에는 Torch 라는 이름으로 Lua 언어 기반으로 만들어졌으나, 이후 Python 기반으로 변경한 것이 Pytorch 이다.
* NewYork 대학교와 FaceBook 이 공동으로 개발하였고, 가장 대중적이면서 널리 사용되는 framework 이다.

In [1]:
import torch
print(torch.__version__)

1.11.0+cu113


### **1-1. Tensor**

* 텐서(Tensor) 는 배열이나 행렬과 매우 유사한 특수한 자료구조이다.
* Pytorch에서는 텐서를 사용하여 모델의 입력과 출력, 그리고 모델의 매개변수들을 부호화하는데 사용된다.

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
import numpy as np

In [4]:
np_array = np.array(data)
x_np_1 = torch.tensor(np_array) # ndarray 를 가져오는 것이 아니라 데이터를 복사해서 가져온다는 것을 확인.
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_np_1[0, 0] = 10
print(x_np_1) 
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[1 2]
 [3 4]]


In [6]:
x_np_2 = torch.as_tensor(np_array) # 뷰( : 같은 데이터를 가리키는 포인터) 를 생성한다.
print(x_np_2)

tensor([[1, 2],
        [3, 4]])


In [7]:
x_np_2[0, 0] = 10 
print(x_np_2) 
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[10  2]
 [ 3  4]]


In [8]:
x_np_3 = torch.from_numpy(np_array) # 뷰 를 생성
print(x_np_3)

tensor([[10,  2],
        [ 3,  4]])


In [9]:
x_np_3[0, 0] = 20
print(x_np_3) 
print(np_array)

tensor([[20,  2],
        [ 3,  4]])
[[20  2]
 [ 3  4]]


In [10]:
# 텐서를 ndarray 로 변경
np_again = x_np_1.numpy()
print(type(np_again))

<class 'numpy.ndarray'>


In [11]:
a = torch.ones(2, 3)
print(a)

b = torch.zeros(2, 3)
print(b)

c = torch.full((2, 3), 2)
print(c)

d = torch.empty(2, 3)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[3.4963e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.0000e+00]])


In [12]:
i = torch.eye(3) # 카탈로그화
print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [13]:
j = torch.arange(10) # 0 ~ x 까지의 숫자를 나열
print(j)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [14]:
k = torch.rand(2, 2)
print(k)
l = torch.randn(2, 2) # 가우시안 정규분포 : 평균을 0으로 하고, 표준편차가 1인 랜덤값 (-2 ~ 2)
print(l)

tensor([[0.7920, 0.5928],
        [0.7684, 0.5405]])
tensor([[-0.8553,  0.7108],
        [-1.0740,  1.1582]])


### **1-2. Tensor 속성**

In [16]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor : {tensor.shape}') # 텐서의 형태
print(f'DataType of tensor : {tensor.dtype}') # 텐서의 데이터타입
print(f'Device of tensor : {tensor.device}') # 텐서를 계산할 때 사용되는 디바이스 : gpu / cpu

Shape of tensor : torch.Size([3, 4])
DataType of tensor : torch.float32
Device of tensor : cpu


In [19]:
# 속성 변경
tensor = tensor.reshape(4, 3)
tensor = tensor.int()
if torch.cuda.is_available() : 
  tensor = tensor.to('cuda')

print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([4, 3])
DataType of tensor : torch.int32
Device of tensor : cpu


### **1-3. Indexing 과 Slicing**

In [20]:
a = torch.arange(1, 13).reshape(3, 4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [21]:
print(a[1])
print(a[0, -1])

tensor([5, 6, 7, 8])
tensor(4)


In [22]:
print(a[1 : -1])

tensor([[5, 6, 7, 8]])


In [23]:
print(a[:2, 2:])

tensor([[3, 4],
        [7, 8]])


### **1-4. Transpose**

In [25]:
a = torch.arange(16).reshape(2, 2, 4)
print(a, a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [26]:
b = a.transpose(1, 2)
print(b, b.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


In [27]:
c = a.permute((2, 0, 1)) # 텐서플로우의 transpose 와 쓰임이 똑같다.
print(c, c.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


### **1-5. Tensor 연산**

In [28]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [30]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)
print('*' * 30)
print(torch.add(x, y))
print(torch.subtract(x, y))
print(torch.multiply(x, y))
print(torch.divide(x, y))
print(torch.matmul(x, y)) # 연산 결과는 같다.

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])
******************************
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [32]:
# in - place 연산
print(x.add(y))
print(x) # 기존의 값이 유지된다.

print(x.add_(y)) # x 에 결과를 다시 저장
# add : x = x + 10, add_ : x += 10
print(x)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])


In [33]:
z = torch.arange(1, 11).reshape(2, 5)
print(z)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [35]:
sum1 = torch.sum(z, axis=0)
sum2 = torch.sum(z, axis=1)
sum3 = torch.sum(z, axis=-1)
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

tensor([ 7,  9, 11, 13, 15]) torch.Size([5])
tensor([15, 40]) torch.Size([2])
tensor([15, 40]) torch.Size([2])


In [36]:
a = torch.arange(24).reshape(4, 6)
b = a.clone().detach() # clone : 복사하기, detach : 붙여넣기. 둘 다 사용해야 함
print(a, a.shape)
print(b, b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
